excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://AbhishekCode.github.io
name: Abhishek
description: Software Developer
author: abhishek singh
avatar: https://avatars2.githubusercontent.com/u/3241861?v=3&s=460
ga_domain: 
ga_tracking_id: 